#!/bin/bash
# backup-db.sh - Encrypted PostgreSQL backup using age.
#
# Produces: /var/backups/auth-api/auth_api_YYYYMMDD_HHMMSS.sql.gz.age
# Requires: age (https://github.com/FiloSottile/age), postgresql-client
#
# Setup:
#   1. Generate a key pair on a secure machine (NOT the DB VPS):
#        age-keygen -o backup.key          # keep this file offline/safe
#        cat backup.key | grep "public"    # copy the public key into AGE_PUBLIC_KEY below
#
#   2. Deploy this script on the DB VPS:
#        sudo cp backup-db.sh /opt/auth-api/backup-db.sh
#        sudo chmod 700 /opt/auth-api/backup-db.sh
#        sudo chown root:root /opt/auth-api/backup-db.sh
#
#   3. Schedule via cron (sudo crontab -e):
#        0 2 * * * /opt/auth-api/backup-db.sh >> /var/log/auth-api-backup.log 2>&1
#
# Restore:
#   age --decrypt -i backup.key auth_api_YYYYMMDD_HHMMSS.sql.gz.age | gunzip | psql auth_api

set -euo pipefail

# -- Configuration ------------------------------------------------------------

DB_NAME="auth_api"
BACKUP_DIR="/var/backups/auth-api"
RETAIN_DAYS=7

# Public key generated by: age-keygen (keep the private key off this server)
AGE_PUBLIC_KEY="age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Optional offsite copy: an rclone remote:path (e.g. "b2:auth-backups").
# Empty skips the upload. Backups that only live on this VPS die with it.
OFFSITE_REMOTE="${OFFSITE_REMOTE:-}"
OFFSITE_RETAIN_DAYS=30

# -- Backup -------------------------------------------------------------------

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="$BACKUP_DIR/${DB_NAME}_${TIMESTAMP}.sql.gz.age"

mkdir -p "$BACKUP_DIR"
chmod 700 "$BACKUP_DIR"

# Dump, compress, encrypt (pipeline: nothing unencrypted touches disk)
sudo -u postgres pg_dump "$DB_NAME" \
    | gzip \
    | age --recipient "$AGE_PUBLIC_KEY" \
    > "$BACKUP_FILE"

chmod 600 "$BACKUP_FILE"

# -- Offsite copy ---------------------------------------------------------------

# The file is already age-encrypted, so the remote never sees plaintext.
if [[ -n "$OFFSITE_REMOTE" ]]; then
    if command -v rclone >/dev/null; then
        rclone copy "$BACKUP_FILE" "$OFFSITE_REMOTE" \
            && echo "$(date -Iseconds) [backup] offsite copy OK - $OFFSITE_REMOTE" \
            || echo "$(date -Iseconds) [backup] WARNING: offsite copy failed" >&2
        # Prune old offsite copies (best-effort).
        rclone delete --min-age "${OFFSITE_RETAIN_DAYS}d" "$OFFSITE_REMOTE" || true
    else
        echo "$(date -Iseconds) [backup] WARNING: OFFSITE_REMOTE set but rclone missing" >&2
    fi
fi

# -- Rotation -----------------------------------------------------------------

find "$BACKUP_DIR" -name "${DB_NAME}_*.sql.gz.age" -mtime +"$RETAIN_DAYS" -delete

# -- Log ----------------------------------------------------------------------

SIZE=$(du -h "$BACKUP_FILE" | cut -f1)
echo "$(date -Iseconds) [backup] OK - $BACKUP_FILE ($SIZE)"
